spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "899822161186-u1mgp3jjrsnimb5ulv0ro79ksnkb6g6v.apps.googleusercontent.com"
            client-secret: "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"
            scope: profile, email
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"

openWeather:
  key: "b6984cc1cea8abd964d364969316e0af"
